### ISSUE TITLE
Consolidate Efforts for Bloc VSCode Extension

### ISSUE THREAD

**Issue by felangel** [Gorniv/vscode-flutter-files#3]
Hey @Gorniv 👋

I'm the maintainer of the [Bloc Library VSCode Extension](https://marketplace.visualstudio.com/items?itemName=FelixAngelov.bloc).

I noticed there's a lot of overlap between your [extension](https://marketplace.visualstudio.com/items?itemName=gornivv.vscode-flutter-files) and the official bloc library extension. I'm wondering if you'd be willing to contribute to the official extension instead of maintaining two separate extensions with overlapping functionality.

Let me know what your thoughts are and thanks!

**Comment by Gorniv** [comment]
Hello @felangel 👋
I am ready to contribute to the official extension, but I have my own idea about the templates for generating files.
I have not yet optimized my code for the extension, since this is essentially a fork https://github.com/ivalexa/vscode-angular2-files, optimized for flutter.
See the results of the "New Big Pack Block".
Let me know what you think, and thank you!

**Comment by felangel** [comment]
Awesome and great job with the extension 👍 

I took a look at the "New Big Pack Block" and it seems to me like it's a very opinionated approach whereas I was thinking of taking a more neutral approach and giving developers the tools to build blocs more quickly but without forcing them to conform to certain app architectures. I personally like what you did with the create individual states/events/blocs more than making assumptions and generating huge chunks of code with all the components integrated in a specific configuration.

Hope that makes sense and let me know what you think?

**Comment by Gorniv** [comment]
Hi @felangel.
Sorry for the long answer.
I think that extension needs to generate big sample code with best practices. It is awesome for beginners.
I really proud BLoC file and "apply" of the event because it is more simple and flexes.
For advanced users, I want to give an opportunity to use a custom template like a folder with templates in the project. And will write example minimal templates.

**Comment by Gorniv** [comment]
@felangel The extension now supports custom templates for the project.
